### ISSUE TITLE
unidentifiable Chinese code

### ISSUE THREAD

**Issue by Masker0827** [RKGalaxy-Luo/Poisson-Surface-Reconstruction-GPU#1]
What encoding format is used for the project (it does not seem to be UTF-8)?
How do I solve the problem of reporting an error due to incorrect coding format

**Comment by RKGalaxy-Luo** [comment]
My project's encoding format is "Chinese Simplified (GB2312) - Codepage 936" as the picture showed below.
![b23696ce-61dd-4e64-be0f-0f6219b41a36](https://github.com/user-attachments/assets/e990331f-e59e-4f47-8ef8-a9a9e0b9a84f)

I'm sorry I annotated the code in Chinese, because it was faster and easier for me to refactor the code.I will finish my to-do list and translate the annotating code to English when I have spare time.
